Repository AminoJS/Amino.JS, pull requests merged in 2018-05, with the labels that each got.

#12 The Wiki Stuff!
  CHANGELOG
  README.md
  examples/commentWikiEntry.js
  examples/createWikiEntry.js
  examples/env.default.js
  helpers/endpoints.js
  helpers/objects.js
  helpers/sorter.js
  helpers/upload.js
  index.js
  modules/commentWikiEntry.js
  modules/createWikiEntry.js
  modules/deleteWikiEntry.js
  modules/login.js
  package.json
  test/index.test.js
  test/modules/getMe.test.js
Labels: MajorUpdate, enhancement

#18 Fetching Community Blog Posts
  examples/env.default.js
  examples/getRecentBlog.js
  helpers/endpoints.js
  helpers/objects.js
  helpers/sorter.js
  index.js
  modules/getCommunityBlogFeed.js
  package-lock.json
  test/index.test.js
Labels: MajorUpdate, enhancement

#25 Fetch User Blogs(Fixed)
  examples/getProfileBlogs.js
  helpers/endpoints.js
  helpers/objects.js
  index.js
  modules/getUserBlogs.js
  test/index.test.js
Labels: MajorUpdate, enhancement

#26 Blog all
  examples/commentPost.js
  examples/commentsPost.js
  examples/deleteBlog.js
  examples/postBlog.js
  helpers/endpoints.js
  helpers/objects.js
  helpers/sorter.js
  index.js
  modules/commentPost.js
  modules/commentsPost.js
  modules/deleteBlog.js
  modules/postBlog.js
  package-lock.json
Labels: MajorUpdate, enhancement

#31 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: MajorUpdate, docsUpdate

#30 Update issue templates
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  LICENSE
Labels: MajorUpdate, docsUpdate

#32 Adding new Testcases
  examples/env.default.js
  helpers/objects.js
  modules/createWikiEntry.js
  test/helpers/loadEnv.js
  test/modules/postBlog.test.js
  test/modules/postWiki.test.js
  test/res/a.png
Labels: MajorUpdate, TravisCI, enhancement
